src/recipe_app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from .views import login_view, logout_view, register_view, delete_user, UserProfileView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('delete-user/', delete_user, name='delete_user'),
    path('profile/<str:username>/', UserProfileView.as_view(), name='profile'),
    path('', include('recipes.urls')), #Home, menu bar, and recipe related views
]

#⚠️NOTE: This only works in development when DEBUG=True
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #For static files (styles.css)

src/recipes/urls.py
from django.urls import path
from .views import homepage, aboutpage, RecipeListView, RecipeDetailView, EditRecipeView, DeleteRecipeView, search_view, add_recipe_view

app_name = 'recipes'

urlpatterns = [
  path('', homepage, name='home'),                              #Home
  path('about/', aboutpage, name='about'),                      #About
  path('list/', RecipeListView.as_view(), name='list'),         #Recipe List
  path('list/<pk>', RecipeDetailView.as_view(), name='detail'), #Recipe Detail
  path('search/', search_view, name='search'),                  #Search Recipe
  path('add/', add_recipe_view, name='add_recipe'),             #Add Recipe
  path('edit/<pk>', EditRecipeView.as_view(), name='edit'),     #Edit Recipe
  path('delete/<pk>', DeleteRecipeView.as_view(), name='delete'),#Delete Recipe
]

src/recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from .storage_backends import MediaStorage  # import MediaStorage
import re


DEBUG_LOG = True

difficulty_choices = (
  #(actual_db_value,human_readable_label)
  ('easy','Easy'),
  ('intermediate','Intermediate'),
  ('hard','Hard')
)

#Function suggestion by ChatGPT for issue of preserving recipes should a user be deleted.
#Gets User row with username 'Deleted User' if exists, else creates it and stores in 'user'.
#Boolen 'created' True if record found, False if record created.
def getDeletedUser():
    user, created = User.objects.get_or_create(
        username='Deleted User', 
        defaults={'password': '','is_active':False}) #setting inactive prevents 'Deleted User' from login
    return user

#Formats recipe titles that may contain ['s] (i.e. Zoey's Casserole)
def smart_title(text):
    # Title-case words
    text = re.sub(r"\b(\w)", lambda m: m.group(1).upper(), text.lower())
    # Correct apostrophe-s (don’t capitalize the s)
    text = re.sub(r"'s\b", "'s", text, flags=re.IGNORECASE)
    return text

# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=50)
    pic = models.ImageField(
        upload_to='recipes', 
        storage=MediaStorage(),   # force Azure storage
        blank=True, 
        null=True
        #default='no_picture.jpg' image handled in templates
    ) 
    cooking_time = models.PositiveIntegerField()
    ingredients = models.TextField()
    instructions = models.TextField(default='1. ')
    difficulty = models.CharField(max_length=12, choices=difficulty_choices, default='intermediate')
    last_update = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        User, 
        on_delete=models.SET(getDeletedUser),
        null=True, #allows for temporary setting field to Null during reassignment
        blank=True #allows for temporary setting field to Null during reassignment
        )

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('recipes:detail', kwargs={'pk': self.pk})

    def get_ingredients_as_list(self):
        ingredient_list = sorted(self.ingredients.split(','))
        return ingredient_list

    #Custom defined save() to correct path to Azure blob 'media/recipes/<filename>'
    def save(self, *args, **kwargs):

        #Normalize name field
        if self.name:
            DEBUG_LOG and print(f'>>>>>> starting name is {self.name}')
            #strip whitespace, title case, correct 'S (i.e. Grandma'S Apple Cake) ⚠️ This does not correct 'S issue
            #cleaned = self.name.strip().title().replace("'S","'s") 
 
            cleaned = smart_title(self.name.strip())
            DEBUG_LOG and print(f'>>>>>> cleaned name is {cleaned}')
            self.name = cleaned
    
        #Normalize ingredients field
        if self.ingredients:
            cleaned = [i.strip().title() for i in self.ingredients.split(',') if i.strip()]
            self.ingredients = ",".join(cleaned)

        DEBUG_LOG and print("💾 Saving Recipe:", self.name)

        super().save(*args, **kwargs)

src/recipes/forms.py
from django import forms
from .models import Recipe

#Form will take an ingredient from user
class IngredientSearchForm(forms.Form):
    ingredient = forms.CharField(
        max_length = 255, 
        required=False)

#Form for adding new recipes in app
class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        # Fields you want to include in the form
        fields = ['name', 'pic', 'cooking_time', 'ingredients', 'instructions', 'difficulty']

        # Optional: customize widgets for styling
        widgets = {
            'name': forms.TextInput(attrs={'class': 'recipe-form-input'}),
            'cooking_time': forms.NumberInput(attrs={'class': 'recipe-form-input'}),
            'ingredients': forms.TextInput(attrs={'class': 'recipe-form-input'}),
            'instructions': forms.Textarea(attrs={'class': 'recipe-form-textarea'}),
            'difficulty': forms.Select(attrs={'class': 'recipe-form-select'}),
        }

src/recipes/views.py
from django.shortcuts import render, redirect

from django.views.generic import ListView, DetailView   #To display list & detail views
from django.views.generic import UpdateView, DeleteView #To allow editing on a recipe

from django.contrib.auth.mixins import LoginRequiredMixin   #To protect class-based views
from django.contrib.auth.decorators import login_required   #To protect function-based views
from django.core.exceptions import PermissionDenied
from django.urls import reverse, reverse_lazy               #For building links in DataFrame

from .models import Recipe                              #Access to Recipe model
from .forms import IngredientSearchForm, RecipeForm
from .utils import recipe_queryset_to_html, get_chart
import pandas as pd
from django.db.models import Count

DEBUG_LOG = False

# Create your views here.

#View function for the recipe application homepage
def homepage(request):
    return render(request, 'recipes/home.html')

#View function for the about page
def aboutpage(request):
    return render(request, 'recipes/about.html')

#Class for recipes list
class RecipeListView(ListView):
    model = Recipe
    template_name = 'recipes/listing.html'

#Class for recipe details
#🔒 PROTECTED VIEW
class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'recipes/detail.html'

#FBV for searching recipes based on ingredient
@login_required #🔒 PROTECTED VIEW
def search_view(request):

    #Create form instance
    form = IngredientSearchForm(request.POST or None)
    recipes_df = None
    recipes_df_html = '' #Initialize DataFrames html to empty string
    
    #Graph variables
    bar_graph = ''
    pie_graph = ''
    line_graph = ''

    #Returns counts for each difficulty as list of dictionaries in
    # the format [{'difficulty':'easy' , 'count':7}, {}, {}]
    difficulty_qs = (
        Recipe.objects
        .values("difficulty")
        .annotate(count=Count("difficulty"))
    )

    line_df = pd.DataFrame(list(difficulty_qs))

    #Line chart: Shows recipe difficulties and totals
    line_graph = get_chart(
        chart_type = "line",
        data = line_df
    )

    #Get all creators and counts for recipes created by each
    creator_qs = (
        Recipe.objects
        .values("created_by__username")
        .annotate(count=Count("created_by"))
    )

    bar_df = pd.DataFrame(list(creator_qs))

    DEBUG_LOG and print(f'*** bar_df["created_by__username"] is\n',bar_df['created_by__username'])
    DEBUG_LOG and print(f'*** bar_df["count"] is\n',bar_df['count'])

    #Bar graph: Shows number of recipes created per user
    bar_graph = get_chart(
        chart_type = "bar",
        data = bar_df
    )

    #Handle form submits
    if request.method == 'POST':
        ingredient = request.POST.get('ingredient')
        #print(f'🥕 Searching for {ingredient}')

        #Empty search returns all recipes
        if ingredient == '':
            qs = Recipe.objects.all()
            recipes_df_html = recipe_queryset_to_html(qs)

        #Otherwise filter recipes to search inredient
        else:
            qs = Recipe.objects.filter(ingredients__icontains=ingredient)

            if qs.exists():
                recipes_df_html = recipe_queryset_to_html(qs)

                #Pie chart: portion of recipes containing the ingredient
                total_recipes = Recipe.objects.count()
                matching_recipes = qs.count()
                non_matching_recipes = total_recipes - matching_recipes

                #Create a DataFrame with labels/values (see utils.py)
                pie_df = pd.DataFrame({
                    'label': [f'{matching_recipes} Contain {ingredient}', f'{non_matching_recipes} Do not contain {ingredient}'],
                    'value': [matching_recipes, non_matching_recipes]
                })

                pie_graph = get_chart(
                    chart_type='pie',
                    data=pie_df,
                )

    #Create context for template
    context = {
        'form':form,
        'recipes_df_html':recipes_df_html,
        'bar_graph':bar_graph,
        'pie_graph':pie_graph,
        'line_graph':line_graph,
        'hide_search_menu':True,
    }

    #Load search template w/context data
    return render(request, 'recipes/search.html', context)


#FBV for adding new recipes for authenticated users.
@login_required #🔒 PROTECTED VIEW
def add_recipe_view(request):
    #Initializations
    error_message = None
    form = RecipeForm()

    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)  # Important: include request.FILES for image uploads
        if form.is_valid():
            recipe = form.save(commit=False)  # Don't save yet
            recipe.created_by = request.user  # Automatically assign the logged-in user
            recipe.save()
            return redirect(recipe.get_absolute_url())
        else:
            # Collect field and non-field errors
            error_message = form.errors

    context = {
        'form': form,
        'error_message': error_message,
        'hide_add_recipe_menu':True,
    }
    return render(request, 'recipes/add_recipe.html', context)

#Class for editing and updating a recipe.
#🔒 PROTECTED VIEW
class EditRecipeView(LoginRequiredMixin, UpdateView):
    model = Recipe
    form_class = RecipeForm
    template_name = 'recipes/edit_recipe.html'

    def dispatch(self, request, *args, **kwargs):
        recipe = self.get_object() #Get the recipe
        if recipe.created_by != request.user:
            raise PermissionDenied("You can't change someone else's recipe.")
        return super().dispatch(request, *args, **kwargs)

#Class view for deleting a recipe.
#🔒 PROTECTED VIEW
class DeleteRecipeView(LoginRequiredMixin, DeleteView):
    model = Recipe
    template_name = 'recipes/confirm_delete.html'
    success_url = reverse_lazy('recipes:list')

    def dispatch(self, request, *args, **kwargs):
        recipe = self.get_object()
        #Ensure owner is the logged in user
        if recipe.created_by != request.user:
            raise PermissionDenied("You can't delete another user's recipe")
        return super().dispatch(request, *args, **kwargs)

src/recipes/templates/recipes/about.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Simmer - About</title>
  <!--Bootstrap CDN-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
</head>

<body>
  <div class="page-container">

    <!--Menubar-->
    {% include 'recipes/partials/menubar.html' %}

    <div class="page-container-row">
      <div class="page-container-header">About Simmer...</div>
    </div>

    <div>
      <div class="about-text-container">
        <p>The <i>Simmer</i> application is part of my journey through the Full-Stack Web Development program through
          CareerFoundry.
          I created this while learning Django basics and plan to maintain this application and make updates with
          additional functionality over time.</p>
        <p>Thanks for stopping by and using <i>Simmer</i>!</p>
        <p>You can see my other work and online portfolio using the button below.</p>
      </div>
    </div>

    <div class="page-container-row">

      <div class="home-container-item-col">
        <div class="home-buttons-row">
          <a href="https://cincinnatikid428.github.io/portfolio-website" class="custom-button">My Portfolio</a>
          <a href="{% url 'recipes:home' %}" class="custom-button">Back to Homepage</a>
          <a href="https://careerfoundry.com" class="custom-button">CareerFoundry</a>
        </div>
      </div>
    </div>
    <div class="page-container-row">
      <a href="{% url 'recipes:home' %}">
        <img src="{% static 'recipes/images/simmer-logo1024x1024.png' %}" class="home-simmer-logo"
          alt="Simmer pot logo" />
      </a>
    </div>

  </div>

  <!-- Bootstrap JS Bundle (required for navbar toggler) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>

</body>

</html>

src/recipes/templates/recipes/add_recipe.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Simmer - Add Recipe</title>
  <!--Bootstrap CDN-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
</head>

<body>
  <div class="page-container">

    <!--Menubar-->
    {% include 'recipes/partials/menubar.html' %}

    <h1>Add a New Recipe</h1>

    <div class="page-container-row">
      <form method="POST" enctype="multipart/form-data" class="recipe-form">
        {% csrf_token %}

        <!-- NAME -->
        <div class="recipe-form-row">
          <label class="recipe-form-label">{{ form.name.label_tag }}</label>
          {{ form.name }}
        </div>

        <!-- COOKING TIME -->
        <div class="recipe-form-row">
          <label class="recipe-form-label">{{ form.cooking_time.label_tag }}(min)</label>
          {{ form.cooking_time }}
        </div>

        <!-- INGREDIENTS -->
        <div class="recipe-form-help">
          <p>
            Ingredients should be listed with a comma separating each ingredient. You do not need a space after each
            comma.
          </p>
          <p>For example:</p>
          <p>
            apples,oranges,peaches,lemons,limes
          </p>
        </div>

        <div class="recipe-form-row">
          <label class="recipe-form-label">{{ form.ingredients.label_tag }}</label>
          {{ form.ingredients }}
        </div>

        <!-- INSTRUCTIONS -->
        <div class="recipe-form-help">
          <p>
            When writing your instructions, for best results in displaying in use a numbered list.
          </p>
          <p>For example:</p>
          <p>
          <ol>
            <li>First do this.</li>
            <li>Next, do this.</li>
            <li>Keep adding instructions like this.</li>
          </ol>
          </p>
        </div>

        <div class="recipe-form-row">
          <label class="recipe-form-label">{{ form.instructions.label_tag }}</label>
          {{ form.instructions }}
        </div>

        <!-- DIFFICULTY (Drop-down) -->
        <div class="recipe-form-row">
          <label class="recipe-form-label">{{ form.difficulty.label_tag }}</label>
          {{ form.difficulty }}
        </div>

        <!-- IMAGE UPLOAD -->
        <div class="recipe-form-row">
          <label class="recipe-form-label">{{ form.pic.label_tag }}</label>
          {{ form.pic }}
        </div>

        <div class="recipe-form-button-row">
          <button type="submit" class="custom-button">Save Recipe</button>
          <a href="{% url 'recipes:list' %}" class="custom-button custom-button-red">Cancel</a>
        </div>
      </form>


      {% if error_message %}
      <div class="form-error">
        {{ error_message }}
      </div>
      {% endif %}
    </div>
  </div>

  <!-- Bootstrap JS Bundle (required for navbar toggler) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>

</body>

</html>

src/recipes/templates/recipes/detail.html
<!DOCTYPE html>
{% load static %}
{% load markdownify %}
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    Simmer - {{recipe.name|title}} Detail
  </title>
  <!--Bootstrap CDN-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
</head>

<body>
  <!--Back to recipe list button-->
  <a href="{% url 'recipes:list' %}" class="custom-button recipe-detail-back-button">&lt; Recipe List</a>


  <div class="page-container">

    <!--Menubar-->
    {% include 'recipes/partials/menubar.html' %}

    <div class="page-container-header">
      {{recipe.name}}
    </div>
    {% if request.user == object.created_by %}
    <div class="page-container-row">
      <!--Edit button-->
      <a href="{% url 'recipes:edit' object.pk %}" class="custom-button">Edit Recipe</a>

      <!--Delete button (with confirm in form)-->
      <form method="POST" action="{% url 'recipes:delete' object.pk %}"
        onsubmit="return confirm('Are you sure you want to delete this recipe?');">
        {% csrf_token %}
        <button type="submit" class="custom-button custom-button-red">
          Delete Recipe
        </button>
      </form>

    </div>
    {% endif %}

    <div class="recipe-detail-image-row">

      <div class="recipe-detail-pic-cell">

        {% if recipe.pic %}
        <img src="{{ recipe.pic.url }}" class="recipe-detail-pic" alt="{{ recipe.name }}">
        {% else %}
        <img src="{% static 'recipes/images/no_picture.jpg' %}" class="recipe-detail-pic" alt="No image">
        {% endif %}

      </div>

      <div class="recipe-detail-text-cell">

        <div class="recipe-detail-row">
          <div class="recipe-detail-label">
            Cook Time:
          </div>
          <div class="recipe-detail-value">
            {{recipe.cooking_time}} min
          </div>
        </div>

        <div class="recipe-detail-row">
          <div class="recipe-detail-label">
            Difficulty:
          </div>
          <div class="recipe-detail-value">
            {{recipe.difficulty|title}}
          </div>
        </div>

        <div class="recipe-detail-row">
          <div class="recipe-detail-label">
            Created By:
          </div>
          <div class="recipe-detail-value">
            {% if recipe.created_by|title != "Deleted User" %}
            <a href="{% url 'profile' recipe.created_by%}"><strong>{{recipe.created_by|title}}</strong></a>
            {% else %}
            <strong>{{recipe.created_by|title}}</strong>
            {% endif %}
          </div>
        </div>

        <div class="recipe-detail-row">
          <div class="recipe-detail-label">
            Last Update:
          </div>
          <div class="recipe-detail-value">
            {{recipe.last_update|date:"m/d/Y"}}
          </div>
        </div>

      </div>
    </div>

    <div class="recipe-detail-row">
      <div class="recipe-detail-ingredient-cell">
        <div class="recipe-detail-ingredients-label">
          Ingredients:
        </div>
      </div>
      <div class="recipe-detail-ingredients-value">
        <ul>
          {% for item in recipe.get_ingredients_as_list %}
          <li>{{item|title}}</li>
          {%endfor%}
        </ul>
      </div>

    </div>

    <div class="recipe-detail-row">
      <div class="recipe-detail-ingredient-cell">
        <div class="recipe-detail-ingredients-label">
          Instructions:
        </div>
      </div>
      <div class="recipe-detail-ingredients-value">
        {{recipe.instructions|markdownify}}
      </div>
    </div>

  </div>

  <!-- Bootstrap JS Bundle (required for navbar toggler) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>

</body>

</html>

src/recipes/templates/recipes/edit_recipe.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Simmer - Edit Recipe</title>
  <!--Bootstrap CDN-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
</head>

<body>
  <div class="page-container">

    <!--Menubar-->
    {% include 'recipes/partials/menubar.html' %}

    <h2>{{ object.name }}</h2>

    <div class="page-container-row">
      <form method="POST" enctype="multipart/form-data" class="recipe-form">
        {% csrf_token %}

        <!-- NAME -->
        <div class="recipe-form-row">
          <label class="recipe-form-label">{{ form.name.label_tag }}</label>
          {{ form.name }}
        </div>

        <!-- COOKING TIME -->
        <div class="recipe-form-row">
          <label class="recipe-form-label">{{ form.cooking_time.label_tag }}(min)</label>
          {{ form.cooking_time }}
        </div>

        <!-- INGREDIENTS -->
        <div class="recipe-form-help">
          <p>
            Ingredients should be listed with a comma separating each ingredient. You do not need a space after each
            comma.
          </p>
          <p>For example:</p>
          <p>
            apples,oranges,peaches,lemons,limes
          </p>
        </div>

        <div class="recipe-form-row">
          <label class="recipe-form-label">{{ form.ingredients.label_tag }}</label>
          {{ form.ingredients }}
        </div>

        <!-- INSTRUCTIONS -->
        <div class="recipe-form-help">
          <p>
            When writing your instructions, use a numbered list for best results in displaying.
          </p>
          <p>For example:</p>
          <p>
          <ol>
            <li>First do this.</li>
            <li>Next, do this.</li>
            <li>Keep adding instructions like this.</li>
          </ol>
          </p>
        </div>

        <div class="recipe-form-row">
          <label class="recipe-form-label">{{ form.instructions.label_tag }}</label>
          {{ form.instructions }}
        </div>

        <!-- DIFFICULTY (Drop-down) -->
        <div class="recipe-form-row">
          <label class="recipe-form-label">{{ form.difficulty.label_tag }}</label>
          {{ form.difficulty }}
        </div>

        <!-- IMAGE UPLOAD -->
        <div class="recipe-form-row">
          <label class="recipe-form-label">Picture:</label>

          <div class="recipe-form-picture-input">
            {% if object.pic %}
            <div style="display:block;">
              <img src="{{ object.pic.url }}" class="recipe-form-image-preview">
            </div>
            {% endif %}
            <div style="display:block;">
              {{ form.pic }}
            </div>
          </div>

        </div>

        <div class="recipe-form-button-row">
          <button type="submit" class="custom-button">Update Recipe</button>
          <a href="{{ object.get_absolute_url }}" class="custom-button custom-button-red">Cancel</a>
        </div>
      </form>


      {% if error_message %}
      <div class="form-error">
        {{ error_message }}
      </div>
      {% endif %}
    </div>
  </div>

  <!-- Bootstrap JS Bundle (required for navbar toggler) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>

</body>

</html>

src/recipes/templates/recipes/home.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Simmer - Home</title>

  <!--Bootstrap CDN-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
</head>

<body>
  <div class="page-container">

    <!--Menubar-->
    {% include 'recipes/partials/menubar.html' %}

    <div class="page-container-row">
      <img src="{% static 'recipes/images/ingredients.jpg' %}" class="home-image" alt="ingredients on table" />
    </div>
    <div class="page-container-row">
      <div class="home-container-item-col">
        <span class="home-welcome-text">Welcome to Simmer!</span>
        <div class="home-buttons-row">
          <a href="{% url 'recipes:list' %}" class="custom-button">View Recipes</a>
          {% if user.is_authenticated %}
          {% else %}
          <a href="{% url 'login' %}" class="custom-button">Login/Sign Up</a>
          {% endif %}
        </div>
      </div>

      <img src="{% static 'recipes/images/simmer-logo1024x1024.png' %}" class="home-simmer-logo"
        alt="Simmer pot logo" />
    </div>

  </div>

  <!-- Bootstrap JS Bundle (required for navbar toggler) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>

</body>

</html>

src/recipes/templates/recipes/listing.html
<!DOCTYPE html>
{% load static %} {%comment %} Needed for loading static css file {% endcomment %}
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    Simmer - Recipe List
  </title>

  <!--Bootstrap CDN-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
</head>

<body>
  <div class="page-container">

    <!--Menubar-->
    {% include 'recipes/partials/menubar.html' %}

    <div class="page-container-header">
      Recipe List:
    </div>

    <div class="recipe-list-row">
      {% for recipe in recipe_list %} {% comment %} Accesses each recipe record in model {% endcomment %}
      <div class="recipe-list-item">
        <div class="recipe-list-pic-cell">
          <a href="{{recipe.get_absolute_url}}">

            {% if recipe.pic %}
            <img src="{{ recipe.pic.url }}" class="recipe-list-pic" alt="{{ recipe.name }}">
            {% else %}
            <img src="{% static 'recipes/images/no_picture.jpg' %}" class="recipe-list-pic" alt="No image">
            {% endif %}

          </a>
        </div>
        <a href="{{recipe.get_absolute_url}}">
          <span class="recipe-list-text">{{recipe.name|title}}</span>
        </a>
      </div>
      {% endfor %}
    </div>

  </div>

  <!-- Bootstrap JS Bundle (required for navbar toggler) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>

</body>

</html>

src/recipes/templates/recipes/search.html
<!DOCTYPE html>
{% load static %} {%comment %} Needed for loading static css file {% endcomment %}
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    Simmer - Search
  </title>
  <!--Bootstrap CDN-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
</head>

<body>
  <div class="page-container">

    <!--Menubar-->
    {% include 'recipes/partials/menubar.html' %}

    <div class="page-container-header">
      Search Recipes by Ingredient:
    </div>

    <div>
      <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="custom-button"
          style="margin-left: auto;margin-right: auto;margin-top:8px;">Search</button>
      </form>
    </div>
    <div>
      {% if recipes_df_html %}
      {{recipes_df_html|safe}}
      <br>
      {% if pie_graph %}
      <img src="data:image/png;base64, {{pie_graph|safe}}" class="responsive-graph">
      {% endif %}
      {% else %}
      <h3>No results</h3>
      {% endif %}
    </div>
    <div>
      <hr>
      {% if line_graph %}
      <h3>Recipe Difficulty Totals</h3>
      <img src="data:image/png;base64, {{line_graph|safe}}" class="responsive-graph">
      {% endif %}
      <hr>
      {% if bar_graph %}
      <h3>Recipes By User</h3>
      <img src="data:image/png;base64, {{bar_graph|safe}}" class="responsive-graph">
      {% endif %}
    </div>

  </div>

  <!-- Bootstrap JS Bundle (required for navbar toggler) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>

</body>

</html>